name: Terragrunt Deployment

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  develop:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/terragrunt-common.yaml
    with:
      tg_dir: 'live/dev'
      environment: 'dev'
      aws_region: 'us-east-1'
      aws_caller_identity: '707809188586'
      tf_version: '1.10.5'
      tg_version: '0.67.0'
      plan: ${{ contains(github.event.head_commit.message, '[plan]') }}
      deploy: ${{ contains(github.event.head_commit.message, '[deploy]') }}
      destroy: ${{ contains(github.event.head_commit.message, '[destroy]') }}

  staging:
    if: github.ref == 'refs/heads/release'    
    uses: ./.github/workflows/terragrunt-common.yaml
    with:
      tg_dir: 'live/stage'
      environment: 'stage'
      aws_region: 'us-east-1'
      aws_caller_identity: '707809188586'
      tf_version: '1.10.5'
      tg_version: '0.67.0'
      plan: ${{ contains(github.event.head_commit.message, '[plan]') }}
      deploy: ${{ contains(github.event.head_commit.message, '[deploy]') }}
      destroy: ${{ contains(github.event.head_commit.message, '[destroy]') }}

  production:
    if: >
      github.event_name == 'push' && github.ref == 'refs/heads/main' ||
      github.event_name == 'pull_request' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main'   
    uses: ./.github/workflows/terragrunt-common.yaml
    with:
      tg_dir: 'live/prod'
      environment: 'prod'
      aws_region: 'us-east-1'
      aws_caller_identity: '707809188586'
      tf_version: '1.10.5'
      tg_version: '0.67.0'
      # plan: ${{ contains(github.event.head_commit.message, '[plan]') }}
      # deploy: ${{ contains(github.event.head_commit.message, '[deploy]') }}
      # destroy: ${{ contains(github.event.head_commit.message, '[destroy]') }}
