name: Terragrunt Deployment

on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - main

jobs:
  develop:
    if: github.ref == 'refs/heads/develop'
    env:
      tf_version: '1.10.5'
      tg_version: '0.67.0'
      aws_region: 'us-east-1'
      aws_caller_identity: '707809188586'  
    uses: ./.github/workflows/terragrunt-common.yaml
    with:
      tg_dir: 'live/dev'
      environment: 'dev'
      aws_region: ${{ env.aws_region }}
      aws_caller_identity: ${{ env.aws_caller_identity }}
      tf_version: ${{ env.tf_version }}
      tg_version: ${{ env.tg_version }}
      deploy: ${{ contains(github.event.head_commit.message, '[deploy]') }}

  staging:
    if: github.ref == 'refs/heads/release'
    env:
      tf_version: '1.10.5'
      tg_version: '0.67.0'
      aws_region: 'us-east-1'
      aws_caller_identity: '707809188586'    
    uses: ./.github/workflows/terragrunt-common.yaml
    with:
      tg_dir: 'live/stage'
      environment: 'stage'
      aws_region: $aws_region
      aws_caller_identity: $aws_caller_identity
      tf_version: $tf_version
      tg_version: $env.tg_version
      deploy: ${{ contains(github.event.head_commit.message, '[deploy]') }}

  production:
    if: github.ref == 'refs/heads/main'
    env:
      tf_version: '1.10.5'
      tg_version: '0.67.0'
      aws_region: 'us-east-1'
      aws_caller_identity: '707809188586'      
    uses: ./.github/workflows/terragrunt-common.yaml
    with:
      tg_dir: 'live/prod'
      environment: 'prod'
      aws_region: $aws_region
      aws_caller_identity: $aws_caller_identity
      tf_version: $tf_version
      tg_version: $tg_version
      deploy: ${{ contains(github.event.head_commit.message, '[deploy]') }}