name: Terragrunt Deployment

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - develop
      - release
  pull_request:
    branches:
      - main

jobs:
  develop:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/terragrunt-common.yaml
    with:
      tg_dir: 'live/dev'
      environment: 'dev'
      aws_region: 'us-east-1'
      aws_caller_identity: '707809188586'
      tf_version: '1.10.5'
      tg_version: '0.67.0'
      deploy: ${{ contains(github.event.head_commit.message, '[deploy]') }}

  staging:
    if: github.ref == 'refs/heads/release'    
    uses: ./.github/workflows/terragrunt-common.yaml
    with:
      tg_dir: 'live/stage'
      environment: 'stage'
      aws_region: 'us-east-1'
      aws_caller_identity: '707809188586'
      tf_version: '1.10.5'
      tg_version: '0.67.0'
      deploy: ${{ contains(github.event.head_commit.message, '[deploy]') }}

  production:
    if: github.ref == 'refs/heads/main'      
    uses: ./.github/workflows/terragrunt-common.yaml
    with:
      tg_dir: 'live/prod'
      environment: 'prod'
      aws_region: 'us-east-1'
      aws_caller_identity: '707809188586'
      tf_version: '1.10.5'
      tg_version: '0.67.0'
      deploy: ${{ contains(github.event.head_commit.message, '[deploy]') }}